### ISSUE TITLE
One high and one medium vulnerability in the JWT module

### ISSUE THREAD

**Issue by brfreekmx** [WebFlight/JWT#13]
During a periodic snyk scan in our project we found that the JWT module contains two jars that contain two vulnerabilities. One High and one Medium vulnerability.

Both vulnerabilities relate to the **jackson-databind-2.10.0.pr3.jar** file

The first with a CVSS score of 8.2 [SNYK-JAVA-COMFASTERXMLJACKSONCORE-1048302](https://app.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-1048302)

The second one with a CSVSS score of 5.9 [SNYK-JAVA-COMFASTERXMLJACKSONCORE-2326698](https://app.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-2326698)

**Comment by rsousa** [comment]
I'm aware the issue was reported a long time ago but:
The latest version of this module uses jackson-databind-2.14.1. 
This version has, to this day, no known CVEs [jackson-databind at Snyk Vulnerability Database](https://security.snyk.io/package/maven/com.fasterxml.jackson.core:jackson-databind)
This issue can be closed.

**Comment by brfreekmx** [comment]
Thank you for the update, I'll close the issue
